name = "chouka"
main = "worker.js"
compatibility_date = "2026-02-24"
keep_vars = true

[[kv_namespaces]]
binding = "KV_CACHE"
id = "adb207beb6464667aa6d5bd6bb9aca18"

[[kv_namespaces]]
binding = "RECENT_REQUESTS"
id = "6a528fb7939f49d684331fac2a19e6df"

[[d1_databases]]
binding = "DB"
database_name = "chouka"
database_id = "e3551f09-570f-4806-ac28-3a927b8d330e"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cloudflare-t1"